# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_game', '0002_auto_20160502_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicker_game',
            name='game_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
